### PR TITLE
updated file

### LINKED ISSUE #18: Feat: Update Readme.md
**What is your issue related to ?**

- [ ] Code
- [ ] Designing
- [x] Documentation
- [ ] Testing/Research
- [ ] Others[please specify]

**Description**
Check for grammatical errors, add relevant badges, stats, tech stack logos, etc.

**Additional context**
[For reference](https://towardsdatascience.com/build-a-stunning-readme-for-your-github-profile-9b80434fe5d7)

### PR DESCRIPTION
**Pull request by yjaiswal05**
## Description

Readme file updated 

## Related Issue

Fixes #18  

## Type of Contribution:

- [ ] Bug fix
- [ ] Coding
- [ ] Design
- [ ] Testing
- [ ] Research
- [ ] Enhancement
- [x] Documentation
- [ ] Other : 

## Checklist:

- [x] I have read README.md and CONTRIBUTION.md
- [x] My Pull request is made against `develop` branch.
- [x] My code/design follows the style/guidelines of this project.
- [x] I have performed a self-review of my own code/design/documentation.
- [x] I have commented my code, particularly in hard-to-understand areas(or gave a proper description about the design).

### CODE REVIEW

**Comment by SHITIZ-AGGARWAL** [comment]
@yjaiswal05 
### Remove this
image

### And keep the discord and youtube badges in the next line
image

**Comment by yjaiswal05** [comment]
I have a doubt... If I edit the readme file and push again will the older file get renewed Or i have to close this pr and make a new one?

**Comment by SHITIZ-AGGARWAL** [comment]
@yjaiswal05 You don't have to create a new Pr
Just make the changes in the same Branch
Changes will automatically reflect

**Comment by yjaiswal05** [comment]
done

**Review by SHITIZ-AGGARWAL — APPROVED** [review]
Good Work

**Comment by yjaiswal05** [comment]
Thank you

**Review by nidhisingh-1 — APPROVED** [review]

**Review by Acash512 — APPROVED** [review]

**Pull request merged**
