### PR TITLE
My partner testing

### LINKED ISSUE #14: Feat: Manual testing of My Partners feature
**What is your issue related to ?**

- [ ] Code
- [ ] Designing
- [x] Documentation
- [x] Testing/Research
- [ ] Others[please specify]

**Description**
Download the apk[[release version](https://github.com/Code-Sauce-Official/FitMate/releases/tag/1.0)] and test all different scenarios for the My Partners feature.

An md file with all the test scenarios you covered. Positive and negative test cases as expected. Each test scenario should be documented as below:
```
### Test1 : Description
**_Screenshot/gif_**<br>
<img src="Link" width="300"/><br>
**_Expected Result_**: <br>
**_Actual Result_**: <br>

### Test2 : Description
**_Screenshot/gif_**<br>
<img src="Link" width="300"/><br>
**_Expected Result_**: <br>
**_Actual Result_**: <br>

and so on
...

```
**Additional context**
Add you markdown(md) file in [Testing folder](https://github.com/Code-Sauce-Official/FitMate/tree/develop/Documentation/Testing)
If you see issues or unexpected behaviour during testing feel free to open an issue

### PR DESCRIPTION
**Pull request by remote007**
## Description

Manual testing of My Partners feature of FitMate.

## Related Issue

Fixes https://github.com/Code-Sauce-Official/FitMate/issues/14

## Type of Contribution:

- [x] Testing
- [x] Research
- [x] Enhancement
- [x] Documentation

## Checklist:

- [x] I have read README.md and CONTRIBUTION.md
- [x] My Pull request is made against `develop` branch.
- [x] My code/design follows the style/guidelines of this project.
- [x] I have performed a self-review of my own code/design/documentation.
- [x] I have commented my code, particularly in hard-to-understand areas(or gave a proper description about the design).

### CODE REVIEW

**Review by Acash512 — CHANGES_REQUESTED** [review]
- In Test 2, Multiple irrelevant requests can now not be sent, if user is already a partner or request has already been sent, toast messages are shown accordingly on pressing the button, See issue #38 

- In Test 3, recent message is blank coz there is no recent msg, as for now just the request has been accepted, and user has been added to your partners, the recent message will update once one of the users send a msg, in expected result you can write that we can set a text like "This is the starting of your conversation with this user" 

-  In Test 6, the online status for the user is now shown See commit #53 , perhaps you are not using the most recent version of app

- Also rectify the spelling mistakes wherever necessary.

**Comment by remote007** [comment]
@Acash512 got it , I'm on it.

**Comment by remote007** [comment]
@Acash512 I've made the changes , please review it.

**Review by Acash512 — APPROVED** [review]
Good work @PadminiRai , thanks for your contribution

**Review by SHITIZ-AGGARWAL — APPROVED** [review]

**Review by yatharthmago01 — APPROVED** [review]

**Pull request merged**
