### PR TITLE
Readme file updated

### LINKED ISSUE #18: Feat: Update Readme.md
**What is your issue related to ?**

- [ ] Code
- [ ] Designing
- [x] Documentation
- [ ] Testing/Research
- [ ] Others[please specify]

**Description**
Check for grammatical errors, add relevant badges, stats, tech stack logos, etc.

**Additional context**
[For reference](https://towardsdatascience.com/build-a-stunning-readme-for-your-github-profile-9b80434fe5d7)

### PR DESCRIPTION
**Pull request by yjaiswal05**
## Description

Readme file is updated with correction and addition of relevant badges

## Related Issue

Fixes #18  

## Type of Contribution:

- [ ] Bug fix
- [ ] Coding
- [ ] Design
- [ ] Testing
- [ ] Research
- [ ] Enhancement
- [x] Documentation
- [ ] Other : 

## Checklist:

- [x] I have read README.md and CONTRIBUTION.md
- [x] My Pull request is made against `develop` branch.
- [x] My code/design follows the style/guidelines of this project.
- [x] I have performed a self-review of my own code/design/documentation.
- [x] I have commented my code, particularly in hard-to-understand areas(or gave a proper description about the design).

### CODE REVIEW

**Comment by SHITIZ-AGGARWAL** [comment]
@yjaiswal05 Your branch is not updated

**Comment by yjaiswal05** [comment]
@SHITIZ-AGGARWAL can you tell me which readme file is creating the conflict as all 3 readme files has same name

**Comment by SHITIZ-AGGARWAL** [comment]
@yjaiswal05 Before making the changes always update your repo. This way, there will be very less chance for conflicts

**Comment by SHITIZ-AGGARWAL** [comment]
I am not able to see any changed file

**Comment by SHITIZ-AGGARWAL** [comment]
If possible make a new updated branch and then commit your changes

**Comment by yjaiswal05** [comment]
Okayy

**Pull request closed without merging**
