### PR TITLE
Tested the manual Taking up of challenges with relevant snapshots

### LINKED ISSUE #11: Feat: Manual testing of taking up Challenges
**What is your issue related to ?**

- [ ] Code
- [ ] Designing
- [x] Documentation
- [x] Testing/Research
- [ ] Others[please specify]

**Description**
Download the apk[[release version](https://github.com/Code-Sauce-Official/FitMate/releases/tag/1.0)] and test all different scenarios for taking up a challenge.

An md file with all the test scenarios you covered. Positive and negative test cases as expected. Each test scenario should be documented as below:

```
### Test1 : Description
**_Screenshot/gif_**<br>
<img src="Link" width="300"/><br>
**_Expected Result_**: <br>
**_Actual Result_**: <br>

### Test2 : Description
**_Screenshot/gif_**<br>
<img src="Link" width="300"/><br>
**_Expected Result_**: <br>
**_Actual Result_**: <br>

and so on
```
**Additional context**
Add you markdown(md) file in [Testing folder](https://github.com/Code-Sauce-Official/FitMate/tree/develop/Documentation/Testing)
`If you see issues or unexpected behaviour during testing feel free to open an issue`

### PR DESCRIPTION
**Pull request by Sakalya100**
## Description
This PR is regarding feature request #11 in which test has been done successfully to check manual taking of various functionalities of challenges and relevant snapshots,gifs have been added

## Related Issue

Fixes #11 

## Type of Contribution:

- [ ] Bug fix
- [ ] Coding
- [ ] Design
- [x] Testing
- [ ] Research
- [ ] Enhancement
- [x] Documentation
- [ ] Other : 

## Checklist:

- [ ] I have read README.md and CONTRIBUTION.md
- [ ] My Pull request is made against `develop` branch.
- [ ] My code/design follows the style/guidelines of this project.
- [x] I have performed a self-review of my own code/design/documentation.
- [ ] I have commented my code, particularly in hard-to-understand areas(or gave a proper description about the design).

### CODE REVIEW

**Comment by Sakalya100** [comment]
@SHITIZ-AGGARWAL when will my PR be reviewed and merged?

**Comment by SHITIZ-AGGARWAL** [comment]
@Sakalya100 Refer [this](https://github.com/Code-Sauce-Official/FitMate/tree/develop/Documentation/Testing) for how tests should be added. You have to make a new folder for snapshots. Also you have only added workflow. Refer [this](https://github.com/Code-Sauce-Official/FitMate/blob/develop/Documentation/Testing/SignUpTesting.md) for seeing the formatting of tests and you have to include tests for every possible scenario.

**Review by SHITIZ-AGGARWAL — CHANGES_REQUESTED** [review]
@Sakalya100 Refer [this](https://github.com/Code-Sauce-Official/FitMate/tree/develop/Documentation/Testing) for how tests should be added. You have to make a new folder for snapshots. Also you have only added workflow. Refer [this](https://github.com/Code-Sauce-Official/FitMate/blob/develop/Documentation/Testing/SignUpTesting.md) for seeing the formatting of tests and you have to include tests for every possible scenario.

**Comment by Sakalya100** [comment]
@SHITIZ-AGGARWAL Okay I will make the necessary changes

**Comment by SHITIZ-AGGARWAL** [comment]
@Sakalya100 Update

**Comment by Sakalya100** [comment]
@SHITIZ-AGGARWAL will be done by tomorrow

**Comment by SHITIZ-AGGARWAL** [comment]
@Sakalya100 any update on this

**Comment by SHITIZ-AGGARWAL** [comment]
Closing due to inactivity

**Pull request closed without merging**
